# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  mattodoapi:
    image: mattodoapi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - C:\Users\Matt\Documents\code\mattodo\src\Mattodo.Api:/config
    ports:
      - 7260:7260